language: python
python:
  - "2.7"
services:
  - mongodb
before_script:
  - mongoimport -d victims -c hashes test/mongo_test_hash.json
  - mongoimport -d victims -c users test/mongo_test_user.json
  - pip install coverage pep8
install:
  - pip install -e src/victims_web 
script:
  - pep8 --repeat src/
  - nosetests --logging-clear-handlers --with-coverage --cover-package=victims_web --cover-min-percentage=0 -v test/*.py
branches:
  only:
    - master
    - deployed
notifications:
  email: false
  irc: "irc.freenode.org#victi.ms"
  skip_join: false
